### ISSUE TITLE
I called the blueprint example in UE4.27 but found that some nodes could not be found. Could you please give a configured project sample project file to download

### ISSUE THREAD

**Issue by Lemondogdog** [gtreshchev/RuntimeSpeechRecognizer#1]
I called the blueprint example in UE4.27 but found that some nodes could not be found. Could you please give a configured project sample project file to download

**Comment by gtreshchev** [comment]
What specific nodes could not be found?  Are you trying to call them from the created speech recognizer as shown in the example image? I'm full of work at the moment, but plan to create more intuitive documentation/live examples at some point in the future.

**Comment by Lemondogdog** [comment]
> What specific nodes could not be found? Are you trying to call them from the created speech recognizer as shown in the example image? I'm full of work at the moment, but plan to create more intuitive documentation/live examples at some point in the future.
Can't find bind Event to On populate Audio Data node and capturable sound wave

**Comment by gtreshchev** [comment]
It comes from the [Runtime Audio Importer](https://github.com/gtreshchev/RuntimeAudioImporter) plugin, so if you want to make the same example, you should install that plugin beforehand, as specified in the documentation. However, Runtime Speech Recognizer doesn't depend directly on it (you can make your own custom solution to input the audio data in PCM 32-bit float format).
