### ISSUE TITLE
The instructions are not really instructions

### ISSUE THREAD

**Issue by NextWorldVR** [gtreshchev/RuntimeSpeechRecognizer#10]
Is ther no Project file at least we can learn from how to use this?  AAn example?  Anything?  

For instruction all there is this: 

Create a Speech Recognizer and set the necessary parameters (CreateSpeechRecognizer, for parameters see [here](https://github.com/gtreshchev/RuntimeSpeechRecognizer/wiki/3.-Recognition-parameter-list)).
Bind to the needed delegates (OnRecognitionFinished, OnRecognizedTextSegment and OnRecognitionError).
Start the speech recognition (StartSpeechRecognition).
Process audio data and wait for results from the delegates (ProcessAudioData).
Stop the speech recognizer when not needed (e.g., after the OnRecognitionFinished broadcast).

**Comment by gtreshchev** [comment]
There are some examples indicated in the documentation, including copyable nodes, descriptions for each parameter, and more. Essentially, all the functionality is based on whisper.cpp.
If you need help investigating something, you can specify what exactly is not documented enough, and I'll address and cover it. 

You can also watch videos published by users of this plugin. For example, you can check out the following: https://youtu.be/d-hwooGATKQ, https://youtu.be/xBs-nXzXwoM (from 6:21 to 16:07).
