### ISSUE TITLE
I face an issue with ProcessAudioData, unable to get it to work right when directly feeding Populated audio data from captured sound wave. 

### ISSUE THREAD

**Issue by vk-explore** [gtreshchev/RuntimeSpeechRecognizer#12]
Testing with Model: "Small" & "English only".
Microphone Properties: 48000 sample rate, 2 channels.
Speech recognition params, I used:
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/14229723/662d2aa8-5c70-40c3-afdd-ca852577184f)

When I feed populated audio data directly to SpeechRecognizer->ProcessAudioData like mentioned in wiki, the recognized words are always {"this","that","you","{Music}" etc}. it is always recognizing random single words that doesn't make sense.

But when I change it to the following way, by accumulating the PCM Data array to be big enough and then feeding to ProcessAudioData, then it provides awesome results, with slight delay of course.
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/14229723/6404c911-c60a-45ab-a9bd-d31b8581fbbf)

But from documentation you provided, the "StepSize" parameter should control the duration of audio data going in for speech processing.  in that case even when Populated audio data is directly feeded to ProcessAudioData, the speech should only process once every 5 seconds (StepSize value) right? But that doesn't seem the case. 

The results are accurate only when the stepSize is >= 5 seconds and when the ProcessAudioData is feeded with a PCMData array with 5 second duration of audio data all at once.

Am I Understanding the "StepSize" param the wrong way? What's the better way to approach this to get accurate results with as much less delay as possible?

Also wanted to know, if there is a way to get TimeStamp along with each recognized Text Segment.

**Comment by gtreshchev** [comment]
To get accurate text segments, there needs to be a pause between recognitions. This is automatically handled in the default streaming setup. When `bLast` is false (as shown in the Blueprint example), text is only recognized every 5 seconds (based on the step size), which gives time to gather audio data internally. So, you don't have to add extra stuff like what's in your screenshot. Just use the default `StepSize` of 5 seconds, or increase if needed, and it will work correctly.

For time stamps, they're not available right now, but it could be a good idea to add them later on.
