### ISSUE TITLE
Get Sample Rate showing error after recent update 

### ISSUE THREAD

**Issue by ZiosMakerspace** [gtreshchev/RuntimeSpeechRecognizer#13]
No longer able to connect Capturable sound wave to 'target' in Get sample rate and further 'return value' to convert integer in float.

Issue cropped up the moment we made the recent August updates to the plugin in Unreal engine 5.1

![issue](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/24478972/fa071b73-f6e6-4519-8050-abf3c73e7c89)

**Comment by gtreshchev** [comment]
I recommend making sure that the `RuntimeAudioImporter` plugin is enabled and that the Capturable Sound Wave variable has the `UCapturableSoundWave` object class.

**Comment by gtreshchev** [comment]
Should be fixed in the latest version of the RuntimeAudioImporter: https://github.com/gtreshchev/RuntimeAudioImporter/commit/6d79a73a8e897d18e5ad2e2e37937d7a3a724444
