### ISSUE TITLE
Unreal Engine 5.3 crash

### ISSUE THREAD

**Issue by ashaytamhane** [gtreshchev/RuntimeSpeechRecognizer#17]
Unreal engine (5.3.1/5.3.2 both) crashes when I try to run the nodes copied from https://blueprintue.com/blueprint/et6u52bm/. I simply copied the nodes on my character BP and added the missing variables. 

Full logs below:

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Containers\ContainerHelpers.cpp] [Line: 8] Trying to resize TArray to an invalid size of 2147483648

UnrealEditor_Core!UE::Core::Private::OnInvalidArrayNum() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Containers\ContainerHelpers.cpp:8]
UnrealEditor_RuntimeSpeechRecognizer!TArray<float,TAlignedHeapAllocator<16> >::ResizeGrow() [D:\RocketSync\5.3.0-27405482+++UE5+Release-5.3\Working\Engine\Source\Runtime\Core\Public\Containers\Array.h:2983]
UnrealEditor_RuntimeSpeechRecognizer!FSpeechRecognizerThread::FPendingAudioData::GetMixedAndResampledAudio() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\RuntimeSpeechRecognizer\Private\SpeechRecognizerThread.cpp:259]
UnrealEditor_RuntimeSpeechRecognizer!FSpeechRecognizerThread::ForceProcessPendingAudioData() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\RuntimeSpeechRecognizer\Private\SpeechRecognizerThread.cpp:542]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6665]
UnrealEditor_CoreUObject!UObject::CallFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1139]
UnrealEditor_CoreUObject!UObject::ProcessContextOpcode() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:3094]
UnrealEditor_CoreUObject!ProcessLocalScriptFunction() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1209]
UnrealEditor_CoreUObject!UObject::ProcessInternal() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1306]
UnrealEditor_CoreUObject!UFunction::Invoke() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:6665]
UnrealEditor_CoreUObject!UObject::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2145]
UnrealEditor_Engine!AActor::ProcessEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:1122]
UnrealEditor_Engine!FLatentActionManager::TickLatentActionForObject() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:314]
UnrealEditor_Engine!FLatentActionManager::ProcessLatentActions() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LatentActionManager.cpp:208]
UnrealEditor_Engine!AActor::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:1540]
UnrealEditor_Engine!AActor::TickActor() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:1516]
UnrealEditor_Engine!FActorTickFunction::ExecuteTick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\Actor.cpp:251]
UnrealEditor_Engine!FTickFunctionTask::DoTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:278]
UnrealEditor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1265]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksNamedThread() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:758]
UnrealEditor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:649]
UnrealEditor_Core!FTaskGraphCompatibilityImplementation::WaitUntilTasksComplete() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:2125]
UnrealEditor_Engine!FTickTaskSequencer::ReleaseTickGroup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:556]
UnrealEditor_Engine!FTickTaskManager::RunTickGroup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\TickTaskManager.cpp:1583]
UnrealEditor_Engine!UWorld::RunTickGroup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:771]
UnrealEditor_Engine!UWorld::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LevelTick.cpp:1515]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1924]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:531]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5825]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by Zaptu3117** [comment]
Exactly the same problem here !!

**Comment by gtreshchev** [comment]
The issue is most likely because once the nodes are copied, UE 5.3 loses the following `SampleRate` parameter as shown in the first screenshot. Please make sure you've specified the correct sample rate there, which is obtained from `GetSampleRate` if you're using the capturable sound wave, as shown in the second screenshot. Regardless, I think it needs a separate check to make sure that the specified sample rate is valid and to push an error indicating that the sample rate isn't specified correctly, just to be safe in this case. I'll address this in the next plugin's update.

As it's possibly in your case:
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/41fa3c1f-0a61-4d3c-91e9-de075e55b886)

As it should be:
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/46410664-c1df-4a01-86a0-576942b34204)

**Comment by ashaytamhane** [comment]
Thanks, that helped resolve the issue.

**Comment by sterrysan** [comment]
Thanks it worked. Kudos to you work bruh @gtreshchev
