### ISSUE TITLE
Assertion failed: CaptureThread == nullptr on CapturableSoundWave->ToggleMute(false)

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [gtreshchev/RuntimeSpeechRecognizer#19]
Hello again,

I am experiencing an issue with the `CapturableSoundWave->ToggleMute(false)`. If I set it to mute (`CapturableSoundWave->ToggleMute(true)`) it works just fine, but when I try to unmute it it crashes with a failed assertion of a Windows library.

I was able to pin it down to the call `AudioCapture.StartStream()` in `Plugins/RuntimeAudioImporter/Source/RuntimeAudioImporter/Private/Sound/CapturableSoundWave.cpp` line `282`. (Crash logs below).

Can you replicate the behavior? Is this specific to my setup?

I'm using the plugin from the commit https://github.com/gtreshchev/RuntimeSpeechRecognizer/commit/47481b5a6b9f836f4e542b61c56adb380a71d091, also I'm on Windows 11 and using Unreal Engine 5.3.

PS: My current solution is to stop and restart the capture, like this:

```cpp
CapturableSoundWave->StopCapture();
CapturableSoundWave->StartCapture(DeviceId);
```

<details><summary>Crash Logs</summary>
<p>

```
Assertion failed: CaptureThread == nullptr [File:D:\build\++UE5\Sync\Engine\Source\Runtime\AudioCaptureImplementations\Windows\AudioCaputureWasapi\Private\WasapiCaptureThread.cpp] [Line: 67]

UnrealEditor_RuntimeAudioImporter!UCapturableSoundWave::ToggleMute() [C:\P4\ricardo_mrkite-ricardo_TDY-RD_main_5595\Plugins\RuntimeAudioImporter\Source\RuntimeAudioImporter\Private\Sound\CapturableSoundWave.cpp:282]
UnrealEditor_Dreamia!UDreamiaCharacterComponent::SetAudioSessionMute() [C:\P4\ricardo_mrkite-ricardo_TDY-RD_main_5595\Plugins\Dreamia\Source\Dreamia\Private\DreamiaCharacterComponent.cpp:302]
UnrealEditor_Dreamia!UDreamiaCharacterComponent::execSetAudioSessionMute() [C:\P4\ricardo_mrkite-ricardo_TDY-RD_main_5595\Plugins\Dreamia\Intermediate\Build\Win64\UnrealEditor\Inc\Dreamia\UHT\DreamiaCharacterComponent.gen.cpp:211]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```
</p>
</details>

**Comment by gtreshchev** [comment]
Hi, can you please update the [RuntimeAudioImporter](https://github.com/gtreshchev/RuntimeAudioImporter) plugin to the latest version? There was a fix about a month ago that addressed that issue: https://github.com/gtreshchev/RuntimeAudioImporter/commit/08fdb6dffb6140b72b5c96c753af6852643bd314

**Comment by gtreshchev** [comment]
Resolved in https://github.com/gtreshchev/RuntimeAudioImporter/commit/08fdb6dffb6140b72b5c96c753af6852643bd314

**Comment by RicardoEPRodrigues** [comment]
Sorry to come back so late. I'll update you when I can. Thank you for the heads up.

**Comment by RicardoEPRodrigues** [comment]
Hey, just got the time to update the plugins. All is well! Great work.
