### ISSUE TITLE
Translate to English parameter does not seem to translate when set to true?

### ISSUE THREAD

**Issue by AliElSaleh** [gtreshchev/RuntimeSpeechRecognizer#20]
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/19608222/f9e1cb12-ab3b-4824-9518-9c74d8683f64)
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/19608222/c7144ee1-fc83-4612-ab74-f35f851fac6e)

**Comment by gtreshchev** [comment]
Are you sure you don't have any error logs? The `SetRecognitionParameters` function can only be called if the speech recognizer hasn't started yet, and if it's not in the process of stopping. Also, ensure that your language model is multilingual (but again, in case of errors - they will be displayed in logs). Another possible scenario is that you might call either `SetStreamingDefaults` or `SetNonStreamingDefaults` after setting the recognition parameters, which overwrites the `bTranslateToEnglish` field to `false` by default.

I'll be publishing a small but fully-fledged project example included in the **Content** folder of the plugin with streaming and file input examples, which may make it easier for you to observe how it is intended to work.

**Comment by AliElSaleh** [comment]
Ahh, that was indeed the case. I had called `SetStreamingDefaults` right after i set the recognition parameters. Thanks a lot, the translation to English now works properly.

**Comment by gtreshchev** [comment]
Good 👍
I may need to modify this behavior to prevent overwriting irrelevant properties. Thanks for raising the issue :)
