### ISSUE TITLE
PackageRunning In Quest3

### ISSUE THREAD

**Issue by hideoutbush** [gtreshchev/RuntimeSpeechRecognizer#21]
Hi,Thank you for developing such a great plug-in, but I have a small question about the StartSpeechRecognition node. I log out the runtime log, but find that the OnStarted event is not executable on quest3 after executing the StartSpeechRecognition node, which, by the way, is successfully packaged into the project file. I would like to ask if there is any solution to enable me to successfully implement speech recognition on quest3?After trying, it is possible to obtain recording permissions and successfully implement speech recognition on Android phones, but it cannot be used on quest3. The StartSpeechRecognition node seems to have big problems, making the model unable to load correctly

**Comment by hideoutbush** [comment]
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/93957385/cb4c332d-daef-45f3-912a-cbacd2c8c7fb)

**Comment by hideoutbush** [comment]
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/93957385/a3a05941-15b8-46a1-9eba-661fc8fafb62)
I would like to ask how to make the plugin load synchronously under the Unreal VR template to avoid the asynchronous load flag running in quest3 error?

**Comment by gtreshchev** [comment]
Should be fixed in the latest commits, thanks for letting me know!
