### ISSUE TITLE
Short Voice Inputs Not Recognized Immediately After Recording Starts

### ISSUE THREAD

**Issue by DLLDev** [gtreshchev/RuntimeSpeechRecognizer#23]
**Environment:**
Unreal Engine Version: 5.3

**Issue Description:**
When attempting to use the Runtime Speech Recognizer plugin to recognize short voice inputs (e.g., single-word commands like "yes"), the plugin fails to detect the input if spoken immediately after pressing the record button followed by stopping the record right after the voice input. The issue does not occur if I speak for a longer period or wait for a brief moment after pressing record before speaking.

**Steps to Reproduce:**

Start the speech recognition session using the "FROM MICROPHONE" functionality included in the demo project of the plugin.
Keep the default settings (Streaming defaults)
Immediately after pressing the "START RECORDING" button, say a short english word like "yes" and then stop recording by pressing "STOP RECORDING".

**Expected Behavior:**
The plugin should be able to recognize short voice inputs spoken immediately after recording starts.

**Actual Behavior:**
The plugin does not recognize the voice input unless I speak for a longer duration or pause for a moment after pressing the record button before speaking.

**Additional Information:**
This issue seems to impact the usability of the plugin for applications that rely on quick voice commands or short inputs.

**Comment by gtreshchev** [comment]
Fixed in https://github.com/gtreshchev/RuntimeSpeechRecognizer/commit/c8f9744e65d3488d7ff7398e620f6a5a4c5e52c9.
