### ISSUE TITLE
Nodes missing in Unreal 5.3.2

### ISSUE THREAD

**Issue by Rusus24** [gtreshchev/RuntimeSpeechRecognizer#24]
Hi, some nodes are missing in unreal 5.3.2.

![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/140593525/68efa186-5842-416b-8f6e-00cd80f3135f)
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/140593525/64e6525a-c4af-4957-9c63-f630e51f88a1)

I tried installing the plugins through marketplace and manually. Nothing worked so far.

**Comment by gtreshchev** [comment]
Hi, please install the RuntimeAudioImporter plugin for these nodes to work (this is also a free and open source plugin that was used in this example)
[GitHub](https://github.com/gtreshchev/RuntimeAudioImporter)
[Marketplace](https://unrealengine.com/marketplace/product/runtime-audio-importer)
