### ISSUE TITLE
Unreal Engine Source does not work with version 5300

### ISSUE THREAD

**Issue by MVandermeide** [gtreshchev/RuntimeSpeechRecognizer#26]
I have downloaded Unreal Engine Source from Epic Games Github account. I have downloaded the release RuntimeSpeechRecognizer5300 and extracted it to a zip. I have created a brand new game directory through Unreal Engine Source. Extracted the plugin to my plugins folder MyGame/Plugins/RuntimeSpeechRecognizer. I have ran Generate Project Files and all other steps for running setup for Unreal Engine Source. Once I attempt to run the project I am told that the modules are out of date and would I like to build then now. After clicking yes and it attempts to build I am met with this error:

Engine modules are out of date, and cannot be compiled while the engine is running. Please build through your IDE.

I have tried manually building everything all to the same result. I have verified that my Unreal Engine Version: Version: 5.3.2-0+UE5

**Comment by gtreshchev** [comment]
If you want to work with UE from sources, you should first manually build the engine (e.g. via Visual Studio if you're on Windows). You could follow [this tutorial](https://dev.epicgames.com/documentation/en-us/unreal-engine/building-unreal-engine-from-source?application_version=5.3) to build the engine, then switch the UE version of your project via the .uproject file to your custom engine build, and afterward build the project itself. And finally you'll be able to open your project correctly.

**Comment by gtreshchev** [comment]
If you want to work with UE from sources, you should first manually build the engine (e.g. via Visual Studio if you're on Windows), you could follow [this tutorial](https://dev.epicgames.com/documentation/en-us/unreal-engine/building-unreal-engine-from-source?application_version=5.3) to build the engine. Then switch the UE version of your project via the .uproject file to your custom engine build, and afterward build the project itself. And finally you'll be able to open your project correctly.

**Comment by MVandermeide** [comment]
I have followed those steps step by step and tried targeting the UE5-Main and 5.3 release branch. I've tried using the 5300 source code and was encountering these issues.

**Comment by gtreshchev** [comment]
The error `Engine modules are out of date, and cannot be compiled while the engine is running. Please build through your IDE.`  indicates that you haven't built the engine from sources, or it was done incorrectly/partially. It's not related to having the plugin under your project or not. Please make sure that the engine is fully built as intended
