### ISSUE TITLE
UE5.3 records just "you"

### ISSUE THREAD

**Issue by marvelmaster** [gtreshchev/RuntimeSpeechRecognizer#27]
The setup for Runtime audio importer and speech recognizer just always recognizes "you"
Tested on UE5.3 blank project freshly activated plugins. Used mic to capture audio.
Worked with same setup on UE5.1

**Comment by Rusus24** [comment]
Had the same issue when Windows had 2 microphones as recognized devices. Even though only one worked, the default device was taken into account and did not have any input. Try investigating there.

**Comment by marvelmaster** [comment]
Yes problem was that UE5.3 changes the input device detection and therefore you have to set your input device manually in the BP

**Comment by marvelmaster** [comment]
Yes problem was that UE5.3 changes the input device detection and therefore you have to set your input device manually in the BP.
