### ISSUE TITLE
Unreal crashes when trying to record from microphone.

### ISSUE THREAD

**Issue by jm18499** [gtreshchev/RuntimeSpeechRecognizer#28]
I tried both unreal 5.2 and 5.3 and cloning the github project and using the marketplace plugin. Same error.

Unhandled Exception: EXCEPTION_ILLEGAL_INSTRUCTION

UnrealEditor_RuntimeSpeechRecognizer!ggml_vec_dot_f16() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\ThirdParty\whisper.cpp\ggml.c:1583]
UnrealEditor_RuntimeSpeechRecognizer!ggml_compute_forward_mul_mat() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\ThirdParty\whisper.cpp\ggml.c:10944]
UnrealEditor_RuntimeSpeechRecognizer!ggml_compute_forward() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\ThirdParty\whisper.cpp\ggml.c:16223]
UnrealEditor_RuntimeSpeechRecognizer!ggml_graph_compute_thread() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\RuntimeSpeechRecognizer\Source\ThirdParty\whisper.cpp\ggml.c:18390]
kernel32
ntdll

**Comment by gtreshchev** [comment]
Hi, this is related to your CPU not supporting some of the instruction sets, such as AVX or AVX2, whose determinations are quite hardcoded [here](https://github.com/gtreshchev/RuntimeSpeechRecognizer/blob/main/Source/RuntimeSpeechRecognizer/Private/SpeechRecognizerPrivate.h) (currently there's no way in UE to identify whether the instruction set is strongly supported or not, and it's done by workarounds and estimations). To fix this, I can recommend modifying or commenting out the instruction sets in the file linked above, such as the AVX or AVX2 definitions.

**Comment by jm18499** [comment]
Thank you everything is working great now.
