### ISSUE TITLE
 Blank Audio returned in Unreal Engine 5.4

### ISSUE THREAD

**Issue by Badashphilosophy** [gtreshchev/RuntimeSpeechRecognizer#29]
Following a Youtube video, I implemented the runtime speech recognition into my game on key press the same way the creator did

It seems to work except that no audio message is returned, it just says "You: [blank here where message should be]". Print string is also returning a value of 0.0

when enable base submix is ticked i do hear my voice back but its quite distorted, when un ticked you wouldnt know anything is happening at all because there is no sound and no string output

A few others in the comments are having the same issue, some finding solutions and yet those solutions dont work for everyone so i thought id ask here

solutions mentioned that have worked for some

1: go to your windows privacy settings and allow access for your mic
2: in the blueprints under the start capture section, experiment with changing device number to a number between 0 and 3 to ensure its capturing from the device you are using.

there are still people there who these fixes didnt work for, anyone have any more ideas?

I know i should look at the documentation but this seems a much quicker way for people to find and solve the issue and or related errors when first setting up voice recognition

**Comment by gtreshchev** [comment]
What I could suggest is changing the `DeviceId` in `StartCapture` to another one. I'll probably include this info on the Troubleshooting wiki page.
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/fef2e398-ae9c-4453-924c-d12632234495)

**Comment by Badashphilosophy** [comment]
i saw your troubleshoot in the dischord and so tried all the numbers but nothing worked.

the weird thing is i can hear my microphone come through when subbase or whatever is checked but its not picking up the string values which i will need for widgets, voice controlled effects and probably for speech recognition blueprints to work. im completely stumped. i can try starting again from scratch but ive already tried twice and same problem both times. there were 2 to 4 comments under your youtube tutorial who were having similar issues as me so hopefully someone figures out a solution, otherwise it seems to be working fine for most people

**Comment by gtreshchev** [comment]
Can you share your logs pls?

**Comment by gtreshchev** [comment]
Also, make sure the sample rate node is properly connected, like this:
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/37760b77-f87c-45e9-b6f1-d69032973c59)

**Comment by gtreshchev** [comment]
Closing for now. If it's still relevant, please reopen the issue.
