### ISSUE TITLE
faster-whisper as custom model failed

### ISSUE THREAD

**Issue by midasberlin** [gtreshchev/RuntimeSpeechRecognizer#30]
hello!
i tried adding https://huggingface.co/guillaumekln/faster-whisper-tiny.en/tree/main  as a custom model. it is a faster implementation of whisper. after loading the custom model i get an error when activating the mic. "The audio data could not be processess to the recognizer since the thread is stopped". any idea why? faster-whisper has a great speed advantage in my python environment...
cheers

edit: i forgot to mention: the error message comes from On_RecognitionError_Event

**Comment by gtreshchev** [comment]
This type of language model isn't supported in the plugin. The plugin is based on [whisper.cpp](https://github.com/ggerganov/whisper.cpp), which assumes [ggml](https://github.com/ggerganov/ggml) language models. You can train the language models manually, or convert the Whisper OpenAI language models into ggml ones, or use the language models listed [here](https://huggingface.co/ggerganov/whisper.cpp/tree/main) or [here](https://huggingface.co/distil-whisper/distil-large-v3-ggml/tree/main).
