### ISSUE TITLE
Compilation Error in UE5.4.3

### ISSUE THREAD

**Issue by SYRollingStone** [gtreshchev/RuntimeSpeechRecognizer#33]
I created an empty project in UE5.4.3 and followed the technical documentation to place the plugin in "[ProjectName]/Plugins/RuntimeSpeechRecognizer". After regenerating the project files, I attempted to build the project, but encountered the following error:
`Using Parallel executor to run 5 action(s)
------ Building 5 action(s) started ------
[1/5] Compile [x64] SpeechRecognizerThread.cpp
11>ggml.c(2611): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_vec_max_f32
11>ggml.c(2627): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_vec_argmax_f32
11>ggml.c(13558): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_soft_max_f32
11>ggml.c(15106): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_flash_attn_ext_f16
11>ggml.c(15137): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_flash_attn_ext_f16
11>ggml.c(15369): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_flash_attn_back_f32
11>ggml.c(15390): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_flash_attn_back_f32
11>ggml.c(15397): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_flash_attn_back_f32
11>ggml.c(16379): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_cross_entropy_loss_f32
11>ggml.c(16477): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_cross_entropy_loss_back_f32
11>ggml.c(13446): Error C4756 : Constant overflow in constant-folding
   while compiling ggml_compute_forward_diag_mask_inf
11>whisper.cpp(7155): Error C4756 : Constant overflow in constant-folding
   while compiling dtw_and_backtrace
11>whisper.cpp(5297): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_sample_token
11>whisper.cpp(5379): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_sample_token_topk
11>whisper.cpp(2856): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_decode_internal
11>whisper.cpp(2863): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_decode_internal
11>whisper.cpp(5010): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5011): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5017): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5020): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5025): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5026): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5030): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5034): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5035): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5036): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5040): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5044): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5056): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5068): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5075): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5078): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5093): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5097): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5110): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5120): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5129): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5136): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5139): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5148): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5153): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5168): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5169): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5180): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5187): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5190): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
11>whisper.cpp(5202): Error C4756 : Constant overflow in constant-folding
   while compiling whisper_process_logits
Total time in Parallel executor: 10.39 seconds
Total execution time: 15.31 seconds
11>Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command "C:\Epic\5.0.3\UE_5.4\Engine\Build\BatchFiles\Build.bat VR_SpeechRecognitionEditor Win64 Development -Project="C:\Users\Administrator\Documents\Unreal Projects\VR_SpeechRecognition\VR_SpeechRecognition.uproject" -WaitMutex -FromMsBuild -architecture=x64" exited with code 6.
`
It seems the issue is related to the ThirdParty components. Could you please advise on how to resolve this? Thank you.

**Comment by gtreshchev** [comment]
What is your used C++ standard?

**Comment by SYRollingStone** [comment]
I tried using C++17 and C++20, but I encountered this error with both.
![image](https://github.com/user-attachments/assets/3c14d7b9-6945-4fdf-96a0-7760333a4677)

**Comment by SYRollingStone** [comment]
I replaced infinity with std::numeric_limits<float>::infinity(), and it compiled successfully.

**Comment by gtreshchev** [comment]
> I replaced infinity with std::numeric_limits<float>::infinity(), and it compiled successfully.

Also, this is a known bug in UE, so please download Windows SDK (e.g. version 10.0.18362) and try again: https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/
