### ISSUE TITLE
Integration with EOS voice

### ISSUE THREAD

**Issue by DHdwilson** [gtreshchev/RuntimeSpeechRecognizer#34]
I have a question about integrating this plugin with a pre-existing integration with the EOS for voice rooms.

I have everything setup for users to join voice rooms and talk.  I'm now trying to see if I can add runtime speech recognition for accessibility purposes.  However I'm running into a problem where the recognized speech is coming back as just asterisks.  I'm unsure if this is an initialization issue on my end or when I convert the array of shorts to floats.  This is all done in C++ not blueprint.

My setup looks like so:
```
	SpeechRecognizer = USpeechRecognizer::CreateSpeechRecognizer();
	const auto SpeechParams = USpeechRecognizer::GetStreamingDefaults();
	SpeechRecognizer->SetRecognitionParameters(SpeechParams);
	SpeechRecognizer->SetLanguage(ESpeechRecognizerLanguage::En);
	SpeechRecognizer->OnRecognizedTextSegmentNative.AddLambda([this](const FString& Str)
	{
		UE_LOG(LogTemp,Warning,TEXT("Recognized text: %s"), *Str);
	});
	SpeechRecognizer->StartSpeechRecognition(FOnSpeechRecognitionStartedStatic::CreateLambda([](bool IsSuccess)
	{
		if(!IsSuccess)
		{
			UE_LOG(LogTemp, Error, TEXT("Failed to start speech recognition"))
		}
	}));
```

I then later register a delegate on my user to get audio buffers and send these to the recognition system

```
	VoiceChatUser->RegisterOnVoiceChatBeforeRecvAudioRenderedDelegate(FOnVoiceChatBeforeRecvAudioRenderedDelegate::FDelegate::CreateLambda([this](TArrayView<int16> PcmSamples, int SampleRate, int Channels, bool bIsSilence, const FString& /*ChannelName*/, const FString& /* PlayerName */)
	{
		this->SpeechRecognizer->ProcessAudioData(Audio::FAlignedFloatBuffer(MoveTemp(PcmSamples)), SampleRate, Channels, false);	
	}));
```

However my logs look like so:

```
LogRuntimeSpeechRecognizer: Recognized text segment: " * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *"
```

Sometimes there are parenthesis.  Oddly sometimes it says it detected "you".  Have you seen others integrate this with EOS RTC and have any tips on where I'm going wrong?

**Comment by gtreshchev** [comment]
Hi! This usually means that the audio data passed isn't correct, and in your case, you should convert the `TArrayView<int16>` to `Audio::FAlignedFloatBuffer`. For example, you can do it like this:
```cpp
#include "DSP/FloatArrayMath.h"

TArrayView<int16> PcmSamples;
Audio::FAlignedFloatBuffer PcmSamples_Float;
PcmSamples_Float.SetNumUninitialized(PcmSamples.Num());
Audio::ArrayPcm16ToFloat(MakeArrayView((int16*)PcmSamples.GetData(), PcmSamples.Num()), PcmSamples_Float);
```

Apart from that, everything looks good to me

**Comment by DHdwilson** [comment]
That did the trick!  Thank you so much!  I'm still working through a few issues with my audio thread crashing but if I get into a roadblock there I'll try opening a new issue.  I appreciate the help :)
