### ISSUE TITLE
Works once only per CreateSpeehRecognizer

### ISSUE THREAD

**Issue by imtrobin** [gtreshchev/RuntimeSpeechRecognizer#6]
Hi, I modified your sample to StartCapture/StopCapture  on keypress. I notice it will work the first time only unless I recreate the CreateSpeechRecognizer everytime I capture. That doesn't seem right to me, can you please confirm.

**Comment by gtreshchev** [comment]
There was a small bug in the RuntimeAudioImporter's CapturableSoundWave that caused such behavior. It has already been fixed on GitHub and will be resolved on the Marketplace side once the update is published. Please let me know if it works fine for you now.

**Comment by imtrobin** [comment]
I updated the runtime audio importer, it seems to have more issues. It does not seem to recognize properly now,

**Comment by imtrobin** [comment]
Getting  a lot of these in the logs

```
Validity of PCM data in memory: Valid, number of PCM frames: 1024, PCM data size: 2048
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 342, num of samples per step: 80000)
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 684, num of samples per step: 80000)
LogRuntimeAudioImporter: Successfully added audio data to streaming sound wave.
Added audio info: SoundWave Basic Info:
Number of channels: 2, sample rate: 48000, duration: 0.021333
PCM Info:
Validity of PCM data in memory: Valid, number of PCM frames: 1024, PCM data size: 2048
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 1026, num of samples per step: 80000)
LogRuntimeAudioImporter: Successfully added audio data to streaming sound wave.
Added audio info: SoundWave Basic Info:
Number of channels: 2, sample rate: 48000, duration: 0.021333
PCM Info:
Validity of PCM data in memory: Valid, number of PCM frames: 1024, PCM data size: 2048
LogRuntimeAudioImporter: Successfully added audio data to streaming sound wave.
Added audio info: SoundWave Basic Info:
Number of channels: 2, sample rate: 48000, duration: 0.021333
PCM Info:
Validity of PCM data in memory: Valid, number of PCM frames: 1024, PCM data size: 2048
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 1368, num of samples per step: 80000)
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 1710, num of samples per step: 80000)
LogRuntimeAudioImporter: Successfully added audio data to streaming sound wave.
Added audio info: SoundWave Basic Info:
Number of channels: 2, sample rate: 48000, duration: 0.021333
PCM Info:
Validity of PCM data in memory: Valid, number of PCM frames: 1024, PCM data size: 2048
LogRuntimeSpeechRecognizer: Pending audio data instead of enqueuing it since it is not enough to fill the step size (pending: 2052, num of samples per step: 80000)
LogRuntimeAudioImporter: Successfully added audio data to streaming sound wave.
Added audio info: SoundWave Basic Info:
Number of channels: 2, sample rate: 48000, duration: 0.021333
```

**Comment by gtreshchev** [comment]
There are no issues in the log provided. If you did everything correctly (based on the provided example), just wait for some time, and you will get the results. Please open a separate issue if you still have something not working there.

**Comment by imtrobin** [comment]
Same issue, the frst time it works. I stop capture, and start capture again, the 2nd time, the EventOnRecognitionError will trigger.

1. Start Capture,  talk, Stop Capture. Works
2. Start Capture, talk, Stop Capture.  EventOnRecognitionError

**Comment by gtreshchev** [comment]
> Same issue, the frst time it works. I stop capture, and start capture again, the 2nd time, the EventOnRecognitionError will trigger.
> 
> 1. Start Capture,  talk, Stop Capture. Works
> 2. Start Capture, talk, Stop Capture.  EventOnRecognitionError

I am quite certain that you are stopping the speech recognizer while attempting to capture and process audio data. Please review these nodes for your specific situation, and it should function correctly. I have recently tested it, and there are no problems with it. Additionally, ensure that you have downloaded the most recent version of the RuntimeAudioImporter plugin.
![image](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/69837452/b16a0afb-8bc5-46c8-a813-690b27ed17ee)

**Comment by imtrobin** [comment]
yes, I do stop the speech recognizer cos I do not want it running all the time. I'm doing for a use case more than just a demo that has 1 talking character always. I move up to the character, start a conversation, and leave. and come back again, that's my use case.

**Comment by gtreshchev** [comment]
If you stop the speech recognizer, make sure you start it before processing the audio data as well, this shouldn't cause any problems as of now. There was an issue with the capturable sound wave from the RuntimeAudioImporter not stopping completely and leading to an inability to start it again, but the speech recognizer itself should behave normally. Let me know if you are still experiencing any issues.

**Comment by imtrobin** [comment]
ok it is working now. thanks
