### ISSUE TITLE
Depoloy build??

### ISSUE THREAD

**Issue by allcontentswe** [gtreshchev/RuntimeSpeechRecognizer#9]
My setting
1.ue5.1~
2.sdk 31~
3.runtime audio / runtime speech 5.1 ~ 5.2
4.https://blueprintue.com/blueprint/et6u52bm/
5.Microphone and other file permissions (Ok)

(Speech to text test)
I tried to use it on Android, but in the print string, it looks like this "!!!!!!!!!!!!!!!!!"
And for Play Editor and Windows Depoloy, Speech works normally

[Android phone  speech PrintString]
![Screenshot_20230612_183756_c](https://github.com/gtreshchev/RuntimeSpeechRecognizer/assets/72277090/26a39a32-6d45-4252-b368-f6bfcab3fab4)

**Comment by gtreshchev** [comment]
Could potentially be fixed by 7056cd6946db9c836db9a5a6a8f7ec089b9139a2, needs testing

**Comment by gtreshchev** [comment]
Hard to say for sure, something could be related to the wrong CPU instruction sets determination on Android, although it's hard to speculate. It seems to depend on the API version somehow, and older API versions produce the errors you mentioned. I recommend you try increasing the language model size and using the `SetSuppressBlank`, `SetSuppressNonSpeechTokens` with the `Value` as `true`, and `SetSpeedUp` with the `Value` as false to improve the results.

**Comment by gtreshchev** [comment]
This issue is most likely fixed in efc29beb0518b9e08d7584837e7b67ef9f6b211b, closing this ticket for now. Please reopen it if you still encounter the same issue.
